# Generated by Django 4.2.7 on 2023-12-05 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('purchased', models.BooleanField(default=False)),
                ('purchased_data', models.DurationField(default=django.utils.timezone.now)),
                ('purchase_price', models.DecimalField(decimal_places=5, max_digits=40)),
            ],
        ),
    ]
