# Generated by Django 4.2.7 on 2023-12-06 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='purchased_data',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
