# Generated by Django 4.2.7 on 2023-12-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0005_rename_list_coin_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
