# Generated by Django 4.2.7 on 2023-12-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0007_alter_coin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.CharField(null=True),
        ),
    ]
